import { pgTable, serial, text, integer, boolean, jsonb, timestamp } from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

// 1. Users table (synced with Firebase Authentication UID)
export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  uid: text("uid").notNull().unique(), // Firebase Auth UID
  email: text("email").notNull(),
  role: text("role").default("admin").notNull(), // "superadmin" | "admin"
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// 2. Bookings table
export const bookings = pgTable("bookings", {
  id: text("id").primaryKey(), // Custom ID generated by app
  name: text("name").notNull(),
  whatsapp: text("whatsapp").notNull(),
  email: text("email").notNull(),
  visitType: text("visit_type").notNull(), // "camping" | "visit"
  checkInDate: text("check_in_date").notNull(),
  checkOutDate: text("check_out_date"),
  numNights: integer("num_nights"),
  numPeople: integer("num_people").notNull(),
  numMotorcycles: integer("num_motorcycles").notNull(),
  numCars: integer("num_cars").notNull(),
  rentals: jsonb("rentals"), // RentalPrices map or Custom Rental selection
  paymentMethod: text("payment_method").notNull(), // "tunai" | "qris"
  totalPrice: integer("total_price").notNull(),
  bookingCode: text("booking_code").notNull().unique(),
  createdAt: text("created_at").notNull(),
  paymentStatus: text("payment_status").default("Belum Bayar"), // "Belum Bayar" | "Lunas" | "Menunggu Validasi"
});

// 3. Feedbacks table
export const feedbacks = pgTable("feedbacks", {
  id: text("id").primaryKey(), // Custom ID generated by app
  name: text("name"),
  message: text("message").notNull(),
  createdAt: text("created_at").notNull(),
});

// 4. Admin Settings table (Single row configuration)
export const adminSettings = pgTable("admin_settings", {
  id: integer("id").primaryKey().default(1), // Always id=1
  youtubeUrl: text("youtube_url").notNull(),
  whatsappUrl: text("whatsapp_url").notNull(),
  facebookUrl: text("facebook_url").notNull(),
  instagramUrl: text("instagram_url").notNull(),
  tiktokUrl: text("tiktok_url").notNull(),
  googleMapsUrl: text("google_maps_url").notNull(),
  ticketInfoImage: text("ticket_info_image").notNull(),
  campingImage: text("camping_image").notNull(),
  paymentImage: text("payment_image").notNull(),
  logoUrl: text("logo_url").notNull(),
  priceCampingPerson: integer("price_camping_person").notNull(),
  priceCampingMotorcycle: integer("price_camping_motorcycle").notNull(),
  priceCampingCar: integer("price_camping_car").notNull(),
  priceVisitPerson: integer("price_visit_person").notNull(),
  priceVisitMotorcycle: integer("price_visit_motorcycle").notNull(),
  priceVisitCar: integer("price_visit_car").notNull(),
  rentalPrices: jsonb("rental_prices").notNull(),
  eTicketActive: boolean("e_ticket_active").default(true),
  disableSupabaseSync: boolean("disable_supabase_sync").default(false),
  gmailAutoReplyActive: boolean("gmail_auto_reply_active").default(false),
  gmailToken: text("gmail_token"),
  rentalItems: jsonb("rental_items"), // Array of { id, name, price }
  formFields: jsonb("form_fields"), // Array of form field config objects
  contentTexts: jsonb("content_texts").notNull(), // Hero titles, descriptions, etc.
});

// 5. Visitor Stats table (Single row configuration)
export const visitorStats = pgTable("visitor_stats", {
  id: integer("id").primaryKey().default(1), // Always id=1
  viewsCount: jsonb("views_count").notNull(), // logs date -> count
  totalViews: integer("total_views").default(0).notNull(),
  totalBookings: integer("total_bookings").default(0).notNull(),
  totalRevenue: integer("total_revenue").default(0).notNull(),
});

// 6. Define relationships
export const usersRelations = relations(users, ({ many }) => ({
  // Define relationships if required later (e.g. tracking who created bookings/settings)
}));
